version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: install hugo
          command: |
            echo Downloading Hugo
            curl -Ls https://github.com/gohugoio/hugo/releases/download/v0.36.1/hugo_0.36.1_Linux-ARM64.tar.gz -o /tmp/hugo.tar.gz
            tar xf /tmp/hugo.tar.gz -C /tmp
            mv /tmp/hugo /usr/bin/hugo
            rm -rf /tmp/hugo*
      - run:
          name: build site
          command: |
            cd src && rm -rf build
            cd src && mkdir build && hugo -d build
      - run:
          name: publish site
          command: |
            . venv/bin/activate
            python publish.py
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

